# Default values for pathmind.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: 839270835622.dkr.ecr.us-east-1.amazonaws.com/pathmind
  tag: prod
  pullPolicy: Always
  command: ["java"]
  args:
    - "-Xmx4096m"
    - "-XX:+UseG1GC"
    - "-Dvaadin.productionMode"
    - "-jar"
    - "/app/pathmind-webapp/target/pathmind-webapp-0.0.1-SNAPSHOT.jar"
    - "--server.port=80"

service:
  type: NodePort
  port: 80

env:
  APPLICATION_URL: https://app.pathmind.com
  INTERCOM_APP_ID: byklc7u3
  WEBSITE_HTTPLOGGING_RETENTION_DAYS: 5
  PATHMIND_LOG_FILE_PATH: /tmp/
  SCM_COMMAND_IDLE_TIMEOUT: 1800
  ENVIRONMENT: prod
  SQS_URL: https://queue.amazonaws.com/839270835622/prod-training-queue.fifo
  S3_BUCKET: prod-training-dynamic-files.pathmind.com
  DB_SECRET_NAME: dburl
  DB_SECRET_KEY: DB_URL
  MODEL_ANALYZER_URL: https://ma.devpathmind.com
  MULTI_AGENT: false
  JOB_MOCK_CYCLE: 0
  SQS_UPDATER_URL: https://sqs.us-east-1.amazonaws.com/839270835622/prod-updater-queue
  SNS_UPDATER_SQS_FILTER_ATTR: prod

readinessprobe:
  httpGet:
    path: /
    port: 80
  initialDelaySeconds: 15
  periodSeconds: 10
  failureThreshold: 10

livenessprobe:
  httpGet:
    path: /
    port: 80
  initialDelaySeconds: 30
  periodSeconds: 15
  
name: pathmind

namespace: default

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
   limits:
     cpu: 2
     memory: 2Gi
   requests:
     cpu: 1
     memory: 1Gi


nodeSelector: {}

tolerations: []

affinity: {}

probes:
  readinessProbe:
    httpGet:
      path: /
      port: 80
    initialDelaySeconds: 15
    periodSeconds: 10
    failureThreshold: 10
  livenessProbe:
    httpGet:
      path: /
      port: 80
    initialDelaySeconds: 30
    periodSeconds: 15
